# Generated by Django 5.0 on 2024-01-08 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='room',
            new_name='space',
        ),
    ]
